# Generated by Django 5.2.5 on 2025-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
