# Generated by Django 5.2.5 on 2025-08-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_shortener', '0002_link_access_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'permissions': [('link_without_expiration', 'Link without expiration'), ('can_change_the_slug', 'Can change the slug'), ('can_view_access_count', 'Can view access count')]},
        ),
    ]
